### PR TITLE
Create attack scinarios

### PR DESCRIPTION
**Pull request by choiyu8**
- Attack by repeating DIS
   1) disrepeat-base : One of N nodes changes to attacker
   2) dismulrepeat-base : Several nodes of N nodes change to attacker

### CODE REVIEW

**Comment by sungminlee114** [comment]
LGTM. But we also have to split the attacks by names or etc. I'll work on it.

**Comment by sungminlee114** [comment]
To prevent conflicts, I've merged the 'Implement-attack-and-log-data' branch into this branch

**Comment by nfi** [comment]
This PR renames `applications/rpl-udp-ids` to `applications/blackhole-attack` but it removes the node source code files `applications/rpl-udp-ids/udp-client.c` and `applications/rpl-udp-ids/udp-server.c` ?

Perhaps we should rename `rpl-udp-ids` in a separate PR?

**Comment by nfi** [comment]
I made a separate PR #4 that renames `rpl-udp-ids` as it is a separate issue from the flooding attack scenario.

If you like, I can help to remove the renaming from this PR?

**Comment by sungminlee114** [comment]
Yes please :)

**Comment by nfi** [comment]
I have updated this PR to exclude the renaming. The directories `applications/flooding-attack` and `services/flooding-attack` should be identical to the original PR. Please let me know if you see any issues, but otherwise I think this PR should be ready to be merged now?

**Comment by sungminlee114** [comment]
I've went through the changes. I think its good to go. Thanks for the updates

**Review by nfi — APPROVED** [review]

**Pull request merged**
